export const MUTATIONS_SIGN_IN_DATA = 'sign-in-mutation-data'
export const MUTATIONS_CLEAR_SIGN_IN_DATA = 'sign-in-mutation-clear-data'
export const ACTION_AUTO_SIGN_IN = 'sign-in-action-auto'
export const ACTION_SIGN_IN = 'sign-in-action'
export const ACTION_START_AUTH_TIMER = 'sign-in-actions-timer'
export const ACTION_REFRESH_AUTH = 'sign-in-actions-refresh'
export const GETTER_SIGN_IN_DEFAULT = 'sign-in-getter-default'
export const GETTER_SIGN_IN_IS_AUTH = 'sign-in-getter-is-authenticated'
export const GETTER_SIGN_IN_GET_ROLE = 'sign-in-getter-get-role'

export const MUTATION_SIGN_UP_DATA = 'sign-up-mutation-data'
export const MUTATIONS_CLEAR_SIGN_UP_DATA = 'sign-up-mutation-clear-data'
export const ACTION_SIGN_UP = 'sign-up-action'
export const GETTER_SIGN_UP_DEFAULT = 'sign-up-getter-default'

export const MUTATION_SIGN_OUT_DATA = 'sign-out-mutation-data'
export const MUTATIONS_CLEAR_SIGN_OUT_DATA = 'sign-out-mutation-clear-data'
export const ACTION_SIGN_OUT = 'sign-out-action'
export const GETTER_SIGN_OUT_DEFAULT = 'sign-out-getter-default'

export const MUTATION_FORGET_PASSWORD_DATA = 'forget-password-mutation-data'
export const MUTATIONS_CLEAR_FORGET_PASSWORD_DATA = 'forget-password-mutation-clear-data'
export const ACTION_FORGET_PASSWORD = 'forget-password-action'
export const GETTER_FORGET_PASSWORD_DEFAULT = 'forget-password-getter-default'

export const MUTATION_ACCOUNT_RECOVER_DATA = 'recover-token-mutation-data'
export const MUTATIONS_CLEAR_ACCOUNT_RECOVER_DATA = 'recover-token-mutation-clear-data'
export const ACTION_ACCOUNT_RECOVER = 'recover-token-action'
export const GETTER_ACCOUNT_RECOVER_DEFAULT = 'recover-token-getter-default'

export const MUTATION_ACCOUNT_ACTIVATION_DATA = 'activation-token-mutation-data'
export const MUTATIONS_CLEAR_ACCOUNT_ACTIVATION_DATA = 'activation-token-mutation-clear-data'
export const ACTION_ACCOUNT_ACTIVATION = 'activation-token-action'
export const GETTER_ACCOUNT_ACTIVATION_DEFAULT = 'activation-token-getter-default'

export const MUTATION_PARCEL_DATA = 'parcel-mutation-data'
export const MUTATIONS_CLEAR_PARCEL_DATA = 'parcel-mutation-clear-data'
export const ACTION_PARCEL_CREATE = 'parcel-action-create'
export const GETTER_PARCEL_DEFAULT = 'parcel-getter-default'

export const MUTATION_CATEGORY_DATA = 'category-mutation-data'
export const MUTATIONS_CLEAR_CATEGORY_DATA = 'category-mutation-clear-data'
export const ACTION_CATEGORY_GET_ALL = 'category-action-get-all'
export const GETTER_CATEGORY_DEFAULT = 'category-getter-default'

export const MUTATION_USER_DATA = 'user-mutation-data'
export const MUTATIONS_CLEAR_USER_DATA = 'user-mutation-clear-data'
export const ACTION_USER_SEARCH = 'user-action-search'
export const GETTER_USER_DEFAULT = 'user-getter-default'
