export const MUTATIONS_SIGN_IN_DATA = 'sign-in-mutation-data'
export const MUTATIONS_CLEAR_SIGN_IN_DATA = 'sign-in-mutation-clear-data'
export const MUTATIONS_CLEAR_SIGN_IN_ERRORS = 'sign-in-mutation-clear-errors'
export const ACTION_AUTO_SIGN_IN = 'sign-in-action-auto'
export const ACTION_SIGN_IN = 'sign-in-action'
export const ACTION_CONFIRM_CHANGES = 'sign-in-confirm-changes-action'
export const ACTION_START_AUTH_TIMER = 'sign-in-actions-timer'
export const ACTION_SETUP_AVATAR = 'sign-in-actions-avatar'
export const ACTION_CHECK_BALANCE = 'sign-in-actions-balance'
export const ACTION_CHECK_PROFILE = 'sign-in-actions-profile-check'
export const ACTION_REFRESH_AUTH = 'sign-in-actions-refresh'
export const GETTER_SIGN_IN_DATA = 'sign-in-getter-data'
export const GETTER_SIGN_IN_DONE = 'sign-in-getter-done'
export const GETTER_SIGN_IN_ERROR = 'sign-in-getter-error'
export const GETTER_SIGN_IN_IS_AUTH = 'sign-in-getter-is-authenticated'
export const GETTER_SIGN_IN_GET_ROLE = 'sign-in-getter-get-role'

export const MUTATION_SIGN_UP_DATA = 'sign-up-mutation-data'
export const MUTATIONS_CLEAR_SIGN_UP_DATA = 'sign-up-mutation-clear-data'
export const MUTATIONS_CLEAR_SIGN_UP_ERRORS = 'sign-up-mutation-clear-errors'
export const ACTION_SIGN_UP = 'sign-up-action'
export const GETTER_SIGN_UP_DATA = 'sign-up-getter-data'
export const GETTER_SIGN_UP_DONE = 'sign-up-getter-done'
export const GETTER_SIGN_UP_ERROR = 'sign-up-getter-error'

export const MUTATION_SIGN_OUT_DATA = 'sign-out-mutation-data'
export const MUTATIONS_CLEAR_SIGN_OUT_DATA = 'sign-out-mutation-clear-data'
export const MUTATIONS_CLEAR_SIGN_OUT_ERRORS = 'sign-out-mutation-clear-errors'
export const ACTION_SIGN_OUT = 'sign-out-action'
export const CLEAR_APP_USEAGE_DATA = 'sign-out-clear-app-useage'
export const GETTER_SIGN_OUT_DATA = 'sign-out-getter-data'
export const GETTER_SIGN_OUT_DONE = 'sign-out-getter-done'
export const GETTER_SIGN_OUT_ERROR = 'sign-out-getter-error'

export const MUTATION_FORGET_PASSWORD_DATA = 'forget-password-mutation-data'
export const MUTATIONS_CLEAR_FORGET_PASSWORD_DATA = 'forget-password-mutation-clear-data'
export const MUTATIONS_CLEAR_FORGET_PASSWORD_ERRORS = 'forget-password-mutation-clear-errors'
export const ACTION_FORGET_PASSWORD = 'forget-password-action'
export const GETTER_FORGET_PASSWORD_DATA = 'forget-password-getter-data'
export const GETTER_FORGET_PASSWORD_DONE = 'forget-password-getter-done'
export const GETTER_FORGET_PASSWORD_ERROR = 'forget-password-getter-error'

export const MUTATION_ACCOUNT_RECOVER_DATA = 'recover-token-mutation-data'
export const MUTATIONS_CLEAR_ACCOUNT_RECOVER_DATA = 'recover-token-mutation-clear-data'
export const MUTATIONS_CLEAR_ACCOUNT_RECOVER_ERRORS = 'recover-token-mutation-clear-errors'
export const ACTION_ACCOUNT_RECOVER = 'recover-token-action'
export const GETTER_ACCOUNT_RECOVER_DATA = 'recover-token-getter-data'
export const GETTER_ACCOUNT_RECOVER_DONE = 'recover-token-getter-done'
export const GETTER_ACCOUNT_RECOVER_ERROR = 'recover-token-getter-error'

export const MUTATION_ACCOUNT_ACTIVATION_DATA = 'activation-token-mutation-data'
export const MUTATIONS_CLEAR_ACCOUNT_ACTIVATION_DATA = 'activation-token-mutation-clear-data'
export const MUTATIONS_CLEAR_ACCOUNT_ACTIVATION_ERRORS = 'activation-token-mutation-clear-errors'
export const ACTION_ACCOUNT_ACTIVATION = 'activation-token-action'
export const GETTER_ACCOUNT_ACTIVATION_DATA = 'activation-token-getter-data'
export const GETTER_ACCOUNT_ACTIVATION_DONE = 'activation-token-getter-done'
export const GETTER_ACCOUNT_ACTIVATION_ERROR = 'activation-token-getter-error'

export const MUTATION_PARCEL_DATA = 'parcel-mutation-data'
export const MUTATIONS_CLEAR_PARCEL_DATA = 'parcel-mutation-clear-data'
export const MUTATIONS_CLEAR_PARCEL_ERRORS = 'parcel-mutation-clear-errors'
export const ACTION_PARCEL_CREATE = 'parcel-action-create'
export const ACTION_PARCEL_SEARCH = 'parcel-action-search'
export const GETTER_PARCEL_DATA = 'parcel-getter-data'
export const GETTER_PARCEL_DATA_CREATE = 'parcel-getter-data-create'
export const GETTER_PARCEL_DATA_SEARCH = 'parcel-getter-data-search'
export const GETTER_PARCEL_DONE = 'parcel-getter-done'
export const GETTER_PARCEL_ERROR = 'parcel-getter-error'

export const MUTATION_CATEGORY_DATA = 'category-mutation-data'
export const MUTATIONS_CLEAR_CATEGORY_DATA = 'category-mutation-clear-data'
export const MUTATIONS_CLEAR_CATEGORY_ERRORS = 'category-mutation-clear-errors'
export const ACTION_CATEGORY_GET_ALL = 'category-action-get-all'
export const GETTER_CATEGORY_DATA = 'category-getter-data'
export const GETTER_CATEGORY_DATA_GET_ALL = 'category-getter-data-get-all'
export const GETTER_CATEGORY_DONE = 'category-getter-done'
export const GETTER_CATEGORY_ERROR = 'category-getter-error'

export const MUTATION_GENDER_DATA = 'gender-mutation-data'
export const MUTATIONS_CLEAR_GENDER_DATA = 'gender-mutation-clear-data'
export const MUTATIONS_CLEAR_GENDER_ERRORS = 'gender-mutation-clear-errors'
export const ACTION_GENDER_GET_ALL = 'gender-action-get-all'
export const GETTER_GENDER_DATA = 'gender-getter-data'
export const GETTER_GENDER_DATA_GET_ALL = 'gender-getter-data-get-all'
export const GETTER_GENDER_DONE = 'gender-getter-done'
export const GETTER_GENDER_ERROR = 'gender-getter-error'

export const MUTATION_PAYOUT_DATA = 'payout-mutation-data'
export const MUTATIONS_CLEAR_PAYOUT_DATA = 'payout-mutation-clear-data'
export const MUTATIONS_CLEAR_PAYOUT_ERRORS = 'payout-mutation-clear-errors'
export const ACTION_PAYOUT_CREATE = 'payout-action-create'
export const GETTER_PAYOUT_DATA = 'payout-getter-data'
export const GETTER_PAYOUT_DATA_CREATE = 'payout-getter-data-create'
export const GETTER_PAYOUT_DONE = 'payout-getter-done'
export const GETTER_PAYOUT_ERROR = 'payout-getter-error'

export const MUTATION_PAYMENT_DATA = 'payment-mutation-data'
export const MUTATIONS_CLEAR_PAYMENT_DATA = 'payment-mutation-clear-data'
export const MUTATIONS_CLEAR_PAYMENT_ERRORS = 'payment-mutation-clear-errors'
export const ACTION_PAYMENT_CREATE = 'payment-action-create'
export const GETTER_PAYMENT_DATA = 'payment-getter-data'
export const GETTER_PAYMENT_DATA_CREATE = 'payment-getter-data-create'
export const GETTER_PAYMENT_DONE = 'payment-getter-done'
export const GETTER_PAYMENT_ERROR = 'payment-getter-error'

export const MUTATION_RATING_DATA = 'rating-mutation-data'
export const MUTATIONS_CLEAR_RATING_DATA = 'rating-mutation-clear-data'
export const MUTATIONS_CLEAR_RATING_ERRORS = 'rating-mutation-clear-errors'
export const ACTION_RATING_CREATE = 'rating-action-create'
export const ACTION_RATING_SEARCH = 'rating-action-search'
export const GETTER_RATING_DATA = 'rating-getter-data'
export const GETTER_RATING_DONE = 'rating-getter-done'
export const GETTER_RATING_ERROR = 'rating-getter-error'

export const MUTATION_USER_DATA = 'user-mutation-data'
export const MUTATIONS_CLEAR_USER_DATA = 'user-mutation-clear-data'
export const MUTATIONS_CLEAR_USER_ERRORS = 'user-mutation-clear-errors'
export const ACTION_USER_CREATE = 'user-action-create'
export const ACTION_USER_UPDATE = 'user-action-update'
export const ACTION_USER_SEARCH = 'user-action-search'
export const ACTION_USER_GET = 'user-action-get'
export const GETTER_USER_DATA = 'user-getter-data'
export const GETTER_USER_DATA_CREATE = 'user-getter-data-create'
export const GETTER_USER_DATA_UPDATE = 'user-getter-data-update'
export const GETTER_USER_DATA_SEARCH = 'user-getter-data-search'
export const GETTER_USER_DATA_GET = 'user-getter-data-get'
export const GETTER_USER_DONE = 'user-getter-done'
export const GETTER_USER_ERROR = 'user-getter-error'

export const MUTATION_PREFERENCE_DATA = 'preference-mutation-data'
export const MUTATIONS_CLEAR_PREFERENCE_DATA = 'preference-mutation-clear-data'
export const MUTATIONS_CLEAR_PREFERENCE_ERRORS = 'preference-mutation-clear-errors'
export const ACTION_PREFERENCE_SEARCH = 'preference-action-search'
export const GETTER_PREFERENCE_DATA = 'preference-getter-data'
export const GETTER_PREFERENCE_DATA_SEARCH = 'preference-getter-data-search'
export const GETTER_PREFERENCE_DONE = 'preference-getter-done'
export const GETTER_PREFERENCE_ERROR = 'preference-getter-error'

export const MUTATION_PLACE_DATA = 'place-mutation-data'
export const MUTATIONS_CLEAR_PLACE_DATA = 'place-mutation-clear-data'
export const MUTATIONS_CLEAR_PLACE_ERRORS = 'place-mutation-clear-errors'
export const ACTION_PLACE_SEARCH = 'place-action-search'
export const GETTER_PLACE_DATA = 'place-getter-data'
export const GETTER_PLACE_DATA_SEARCH = 'place-getter-data-search'
export const GETTER_PLACE_DONE = 'place-getter-done'
export const GETTER_PLACE_ERROR = 'place-getter-error'

export const MUTATION_SHIPMENT_DATA = 'shipment-mutation-data'
export const MUTATIONS_CLEAR_SHIPMENT_DATA = 'shipment-mutation-clear-data'
export const MUTATIONS_CLEAR_SHIPMENT_ERRORS = 'shipment-mutation-clear-errors'
export const ACTION_SHIPMENT_SEARCH = 'shipment-action-search'
export const ACTION_SHIPMENT_CREATE = 'shipment-action-create'
export const GETTER_SHIPMENT_DATA = 'shipment-getter-data'
export const GETTER_SHIPMENT_DATA_CREATE = 'shipment-getter-data-create'
export const GETTER_SHIPMENT_DATA_SEARCH = 'shipment-getter-data-search'
export const GETTER_SHIPMENT_DONE = 'shipment-getter-done'
export const GETTER_SHIPMENT_ERROR = 'shipment-getter-error'

export const MUTATION_PRICE_DATA = 'price-mutation-data'
export const MUTATIONS_CLEAR_PRICE_DATA = 'price-mutation-clear-data'
export const MUTATIONS_CLEAR_PRICE_ERRORS = 'price-mutation-clear-errors'
export const ACTION_PRICE_GET = 'price-action-get'
export const GETTER_PRICE_DATA = 'price-getter-data'
export const GETTER_PRICE_DATA_GET = 'price-getter-data-get'
export const GETTER_PRICE_DONE = 'price-getter-done'
export const GETTER_PRICE_ERROR = 'price-getter-error'

export const MUTATION_INVOICE_DATA = 'invoice-mutation-data'
export const MUTATIONS_CLEAR_INVOICE_DATA = 'invoice-mutation-clear-data'
export const MUTATIONS_CLEAR_INVOICE_ERRORS = 'invoice-mutation-clear-errors'
export const ACTION_INVOICE_DOWNLOAD = 'invoice-action-download'
export const GETTER_INVOICE_DATA = 'invoice-getter-data'
export const GETTER_INVOICE_DONE = 'invoice-getter-done'
export const GETTER_INVOICE_ERROR = 'invoice-getter-error'

export const MUTATION_LOCATION_DATA = 'location-mutation-data'
export const MUTATIONS_CLEAR_LOCATION_DATA = 'location-mutation-clear-data'
export const MUTATIONS_CLEAR_LOCATION_ERRORS = 'location-mutation-clear-errors'
export const ACTION_LOCATION_GET = 'location-action-get'
export const GETTER_LOCATION_DATA = 'location-getter-data'
export const GETTER_LOCATION_ERROR = 'location-getter-error'
