export const MUTATIONS_SIGN_IN_DATA = 'sign-in-mutation-data'
export const MUTATIONS_CLEAR_SIGN_IN_DATA = 'sign-in-mutation-clear-data'
export const MUTATIONS_CLEAR_SIGN_IN_ERRORS = 'sign-in-mutation-clear-errors'
export const ACTION_AUTO_SIGN_IN = 'sign-in-action-auto'
export const ACTION_SIGN_IN = 'sign-in-action'
export const ACTION_START_AUTH_TIMER = 'sign-in-actions-timer'
export const ACTION_SETUP_AVATAR = 'sign-in-actions-avatar'
export const ACTION_CHECK_BALANCE = 'sign-in-actions-balance'
export const ACTION_CHECK_PROFILE = 'sign-in-actions-profile-check'
export const ACTION_REFRESH_AUTH = 'sign-in-actions-refresh'
export const GETTER_SIGN_IN_DATA = 'sign-in-getter-data'
export const GETTER_SIGN_IN_DONE = 'sign-in-getter-done'
export const GETTER_SIGN_IN_ERROR = 'sign-in-getter-error'
export const GETTER_SIGN_IN_IS_AUTH = 'sign-in-getter-is-authenticated'
export const GETTER_SIGN_IN_GET_ROLE = 'sign-in-getter-get-role'

export const MUTATION_SIGN_UP_DATA = 'sign-up-mutation-data'
export const MUTATIONS_CLEAR_SIGN_UP_DATA = 'sign-up-mutation-clear-data'
export const MUTATIONS_CLEAR_SIGN_UP_ERRORS = 'sign-up-mutation-clear-errors'
export const ACTION_SIGN_UP = 'sign-up-action'
export const GETTER_SIGN_UP_DATA = 'sign-up-getter-data'
export const GETTER_SIGN_UP_DONE = 'sign-up-getter-done'
export const GETTER_SIGN_UP_ERROR = 'sign-up-getter-error'

export const MUTATION_SIGN_OUT_DATA = 'sign-out-mutation-data'
export const MUTATIONS_CLEAR_SIGN_OUT_DATA = 'sign-out-mutation-clear-data'
export const MUTATIONS_CLEAR_SIGN_OUT_ERRORS = 'sign-out-mutation-clear-errors'
export const ACTION_SIGN_OUT = 'sign-out-action'
export const GETTER_SIGN_OUT_DATA = 'sign-out-getter-data'
export const GETTER_SIGN_OUT_DONE = 'sign-out-getter-done'
export const GETTER_SIGN_OUT_ERROR = 'sign-out-getter-error'

export const MUTATION_FORGET_PASSWORD_DATA = 'forget-password-mutation-data'
export const MUTATIONS_CLEAR_FORGET_PASSWORD_DATA = 'forget-password-mutation-clear-data'
export const MUTATIONS_CLEAR_FORGET_PASSWORD_ERRORS = 'forget-password-mutation-clear-errors'
export const ACTION_FORGET_PASSWORD = 'forget-password-action'
export const GETTER_FORGET_PASSWORD_DATA = 'forget-password-getter-data'
export const GETTER_FORGET_PASSWORD_DONE = 'forget-password-getter-done'
export const GETTER_FORGET_PASSWORD_ERROR = 'forget-password-getter-error'

export const MUTATION_ACCOUNT_RECOVER_DATA = 'recover-token-mutation-data'
export const MUTATIONS_CLEAR_ACCOUNT_RECOVER_DATA = 'recover-token-mutation-clear-data'
export const MUTATIONS_CLEAR_ACCOUNT_RECOVER_ERRORS = 'recover-token-mutation-clear-errors'
export const ACTION_ACCOUNT_RECOVER = 'recover-token-action'
export const GETTER_ACCOUNT_RECOVER_DATA = 'recover-token-getter-data'
export const GETTER_ACCOUNT_RECOVER_DONE = 'recover-token-getter-done'
export const GETTER_ACCOUNT_RECOVER_ERROR = 'recover-token-getter-error'

export const MUTATION_ACCOUNT_ACTIVATION_DATA = 'activation-token-mutation-data'
export const MUTATIONS_CLEAR_ACCOUNT_ACTIVATION_DATA = 'activation-token-mutation-clear-data'
export const MUTATIONS_CLEAR_ACCOUNT_ACTIVATION_ERRORS = 'activation-token-mutation-clear-errors'
export const ACTION_ACCOUNT_ACTIVATION = 'activation-token-action'
export const GETTER_ACCOUNT_ACTIVATION_DATA = 'activation-token-getter-data'
export const GETTER_ACCOUNT_ACTIVATION_DONE = 'activation-token-getter-done'
export const GETTER_ACCOUNT_ACTIVATION_ERROR = 'activation-token-getter-error'

export const MUTATION_PARCEL_DATA = 'parcel-mutation-data'
export const MUTATIONS_CLEAR_PARCEL_DATA = 'parcel-mutation-clear-data'
export const MUTATIONS_CLEAR_PARCEL_ERRORS = 'parcel-mutation-clear-errors'
export const ACTION_PARCEL_CREATE = 'parcel-action-create'
export const ACTION_PARCEL_SEARCH = 'parcel-action-search'
export const GETTER_PARCEL_DATA = 'parcel-getter-data'
export const GETTER_PARCEL_DATA_CREATE = 'parcel-getter-data-create'
export const GETTER_PARCEL_DATA_SEARCH = 'parcel-getter-data-search'
export const GETTER_PARCEL_DONE = 'parcel-getter-done'
export const GETTER_PARCEL_ERROR = 'parcel-getter-error'

export const MUTATION_CATEGORY_DATA = 'category-mutation-data'
export const MUTATIONS_CLEAR_CATEGORY_DATA = 'category-mutation-clear-data'
export const MUTATIONS_CLEAR_CATEGORY_ERRORS = 'category-mutation-clear-errors'
export const ACTION_CATEGORY_GET_ALL = 'category-action-get-all'
export const GETTER_CATEGORY_DATA = 'category-getter-data'
export const GETTER_CATEGORY_DATA_GET_ALL = 'category-getter-data-get-all'
export const GETTER_CATEGORY_DONE = 'category-getter-done'
export const GETTER_CATEGORY_ERROR = 'category-getter-error'

export const MUTATION_USER_DATA = 'user-mutation-data'
export const MUTATIONS_CLEAR_USER_DATA = 'user-mutation-clear-data'
export const MUTATIONS_CLEAR_USER_ERRORS = 'user-mutation-clear-errors'
export const ACTION_USER_SEARCH = 'user-action-search'
export const ACTION_USER_GET = 'user-action-get'
export const GETTER_USER_DATA = 'user-getter-data'
export const GETTER_USER_DATA_SEARCH = 'user-getter-data-search'
export const GETTER_USER_DATA_GET = 'user-getter-data-get'
export const GETTER_USER_DONE = 'user-getter-done'
export const GETTER_USER_ERROR = 'user-getter-error'

export const MUTATION_PREFERENCES_DATA = 'preferences-mutation-data'
export const MUTATIONS_CLEAR_PREFERENCES_DATA = 'preferences-mutation-clear-data'
export const MUTATIONS_CLEAR_PREFERENCES_ERRORS = 'preferences-mutation-clear-errors'
export const ACTION_PREFERENCES_SEARCH = 'preferences-action-search'
export const GETTER_PREFERENCES_DATA = 'preferences-getter-data'
export const GETTER_PREFERENCES_DATA_SEARCH = 'preferences-getter-data-search'
export const GETTER_PREFERENCES_DONE = 'preferences-getter-done'
export const GETTER_PREFERENCES_ERROR = 'preferences-getter-error'

export const MUTATION_PLACES_DATA = 'places-mutation-data'
export const MUTATIONS_CLEAR_PLACES_DATA = 'places-mutation-clear-data'
export const MUTATIONS_CLEAR_PLACES_ERRORS = 'places-mutation-clear-errors'
export const ACTION_PLACES_SEARCH = 'places-action-search'
export const GETTER_PLACES_DATA = 'places-getter-data'
export const GETTER_PLACES_DATA_SEARCH = 'places-getter-data-search'
export const GETTER_PLACES_DONE = 'places-getter-done'
export const GETTER_PLACES_ERROR = 'places-getter-error'

export const MUTATION_SHIPMENTS_DATA = 'shipment-mutation-data'
export const MUTATIONS_CLEAR_SHIPMENTS_DATA = 'shipment-mutation-clear-data'
export const MUTATIONS_CLEAR_SHIPMENTS_ERRORS = 'shipment-mutation-clear-errors'
export const ACTION_SHIPMENTS_SEARCH = 'shipment-action-search'
export const ACTION_SHIPMENTS_CREATE = 'shipment-action-create'
export const GETTER_SHIPMENTS_DATA = 'shipment-getter-data'
export const GETTER_SHIPMENTS_DATA_CREATE = 'shipment-getter-data-create'
export const GETTER_SHIPMENTS_DATA_SEARCH = 'shipment-getter-data-search'
export const GETTER_SHIPMENTS_DONE = 'shipment-getter-done'
export const GETTER_SHIPMENTS_ERROR = 'shipment-getter-error'

export const MUTATION_PRICES_DATA = 'price-mutation-data'
export const MUTATIONS_CLEAR_PRICES_DATA = 'price-mutation-clear-data'
export const MUTATIONS_CLEAR_PRICES_ERRORS = 'price-mutation-clear-errors'
export const ACTION_PRICES_GET = 'price-action-get'
export const GETTER_PRICES_DATA = 'price-getter-data'
export const GETTER_PRICES_DATA_GET = 'price-getter-data-get'
export const GETTER_PRICES_DONE = 'price-getter-done'
export const GETTER_PRICES_ERROR = 'price-getter-error'

export const MUTATION_LOCATION_DATA = 'location-mutation-data'
export const MUTATIONS_CLEAR_LOCATION_DATA = 'location-mutation-clear-data'
export const MUTATIONS_CLEAR_LOCATION_ERRORS = 'location-mutation-clear-errors'
export const ACTION_LOCATION_GET = 'location-action-get'
export const GETTER_LOCATION_DATA = 'location-getter-data'
export const GETTER_LOCATION_ERROR = 'location-getter-error'
